// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrs8Y2hL-uje2iphdsOYg_ePzyK-PXosc',
    appId: '1:214775515658:web:3f99083afcfd8ef2b9adf3',
    messagingSenderId: '214775515658',
    projectId: 'fir-5d063',
    authDomain: 'fir-5d063.firebaseapp.com',
    storageBucket: 'fir-5d063.appspot.com',
    measurementId: 'G-73NE8KXN6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcrRjqttjQd-uk8Yx24SkHmzvv-2YW6Y',
    appId: '1:214775515658:android:a916a942f0e2a454b9adf3',
    messagingSenderId: '214775515658',
    projectId: 'fir-5d063',
    storageBucket: 'fir-5d063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDHbIksXy42B251cr-vk8u0RSdFkYsxCI',
    appId: '1:214775515658:ios:fb59e7f1ef94cda2b9adf3',
    messagingSenderId: '214775515658',
    projectId: 'fir-5d063',
    storageBucket: 'fir-5d063.appspot.com',
    iosBundleId: 'com.example.youtubeClone',
  );
}
